apiVersion: network.openshift.io/v1
kind: EgressNetworkPolicy
metadata:
  name: block-external-access
spec:
  egress:
    - type: Allow
      to:
        cidrSelector: 142.44.140.12/32

    - type: Allow
      to:
        dnsName: "www.redhat.com"

    - type: Deny
      to:
        cidrSelector: 0.0.0.0/0
