apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-admin
spec:
  selector:
    matchLabels:
      app: ui-admin
  replicas: 1
  template:
    metadata:
      labels:
        app: ui-admin
        role: ui
        scope: admin
    spec:
      containers:
        - name: pythonapp
          image: pythonapp:v1
          env:
            - name: LISTEN_PORT
              value: "8080"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 512Mi
          ports:
            - containerPort: 8080
