apiVersion: v1
kind: Service
metadata:
  name: request-service
spec:
  selector:
    app: request-service
  ports:
    - protocol: TCP
      name: request
      port: 9004
      targetPort: 9004
    - protocol: TCP
      name: dev-test
      port: 9005
      targetPort: 9005
