kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: billing-service
spec:
  path: /
  to:
    kind: Service
    name: billing-service
    weight: 100
  port:
    targetPort: 9002
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
